### ISSUE TITLE
Icon Loge does't render

### ISSUE THREAD

**Issue by vesnx** [Embarcadero/RADServer-Docs#1]
Miner detail perhaps, but the icon located at:
https://dtffvb2501i0o.cloudfront.net/images/logos/logo-page/rad-server-logo-1024.png

It doesn't work as it doesn't exist. 
```
  <a href="https://www.embarcadero.com/products/rad-server">
    <img src="https://dtffvb2501i0o.cloudfront.net/images/logos/logo-page/rad-server-logo-1024.png" alt="Logo" width="80" height="80">
  </a>
```

**Comment by azapater** [comment]
Good catch! thank you for the report @vesnx
